### ISSUE TITLE
Fake Block does not grab correct color for minecraft:grass

### ISSUE THREAD

**Issue by GreatestFool** [henkelmax/fake-blocks#5]
**Bug description**
The grass blocks do not show the correct color when faked.

**Expected behavior**
Similar color to normal grass blocks and not gray.

**Versions**
- Minecraft: v1.16.5
- Forge: v36.1.10
- Mod: v1.0.2

**Other mods**
I have a few other mods, but I doubt they cause this issue.
- Jade: v2.7.1
- Jade (Waila): v2.7.1
- Item Zoom: v2.3.0
- Just Enough Items: v7.7.0.99
- KubeJS: v1605.3.10-build.8

It still happens even if all other mods than Fake Blocks are disabled.
Also happens in newly generated worlds (tested just in case).

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/3003484/119689747-65846e80-be49-11eb-8d6a-05fe30ea24e0.png)

Not really sure what the deal is with Jade, but it appears as two separate mods in the mod list.
![image](https://user-images.githubusercontent.com/3003484/119689986-9a90c100-be49-11eb-97ea-78380f007a0e.png)

**Comment by henkelmax** [comment]
This mod currently only supports WAILA

**Comment by GreatestFool** [comment]
This happens irregardless of whether or not Waila, Hwyla, Jade or The One Probe. The issue persists, but I mentioned it so you'd know why the list of mods included Jade twice.

I notice I had a giant brain fart however, as I forgot to edit the other issue I copied. Sorry bout' that, I've updated the OP with the correct information.
